# Generated by Django 6.0.2 on 2026-02-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
