# Generated by Django 6.0.2 on 2026-02-20 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apartment_address_alter_apartment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Profiles'),
            preserve_default=False,
        ),
    ]
